<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title><?php echo $this->page['title']; ?></title>
</head>
<body>

<h1><?php echo $this->page['title']; ?></h1>
<h1><?php echo $this->id; ?></h1>
<em><?php echo $this->page['slug']; ?></em>
<p><?php echo $this->page['content']; ?>

    
</body>
</html>